baseURL = "https://munich-nlp.github.io/"
languageCode = "en"
title = "Munich NLP"
theme = "hugo-initio"

[params]
    name = "Munich NLP"
    description = ""
    email = ""
    phone = ""
    address = ""
    year = 2022
    avatar = "images/munichnlp.png"
    avatarclass = ""
    background = ""
    banner = ""
    favicon = ""
    DateForm = ""
    author = ""

    showSubheader = true
    showUpcomingEvents = true
    showPastEvents = true
    showPartners = false
    showOrganizers = true

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1
[[menu.main]]
    name = "Upcoming events"
    url = "/#upcomingevents"
    weight = 5
[[menu.main]]
    name = "Past events"
    url = "/#pastevents"
    weight = 9
[[menu.main]]
    name = "Partners"
    url = "/#partners"
    weight = 13
[[menu.main]]
    name = "Organizers"
    url = "/#organizers"
    weight = 17

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
    title = "discord"
    url = "https://discord.com/invite/BgFaZgZ38N"
    icon = "fab fa-discord"
    footer = true
    sharethis = true
    network = "discord"
[[params.social]]
    title = "youtube"
    url = "https://www.youtube.com/channel/UCmpRQbcw7dOiXSyWpGYwk3Q"
    icon = "fab fa-youtube"
    footer = true
    sharethis = true
    network = "youtube"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/munichnlp"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/company/munich-nlp/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/Munich-NLP"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = "github"
[[params.social]]
	title = "email"
	url = "mailto:munichnlp@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"

